### ISSUE TITLE
Also remove Object.freeze?

### ISSUE THREAD

**Issue by developit** [futurist/rollup-plugin-es3#1]
Rollup calls `Object.freeze()` on exports when using wildcard imports, which also breaks in IE9-.  Thinking it could be stripped out the same way.

**Comment by futurist** [comment]
Added, please check https://github.com/futurist/rollup-plugin-es3/commit/3e3e5f07a3dd700b93cbef666743c68d62f249cf

**Comment by developit** [comment]
Hmm - it seems to break sourceMaps?

**Comment by developit** [comment]
Here's the change: https://github.com/developit/preact-redux/commit/6a4ac37f792e31622ca9bfe4029ee691dfada199
And here's the build failure: https://travis-ci.org/developit/preact-redux/jobs/153546541

**Comment by developit** [comment]
Sent a PR (#2).

**Comment by futurist** [comment]
Merged, thank you!
